### ISSUE TITLE
Two small changes required for set up

### ISSUE THREAD

**Issue by maddybvh** [claudebarde/taquito-pinata-tezos-nft#1]
Hi @claudebarde , thanks for the great article! I ran into two small issues setting this up locally. 

I'm not able to submit a PR, but in case anyone comes across this, these are the changes I needed to make:

In `backend/src/index.ts`:
```
-  const PinataKeys = require("./PinataKeys");
+  const PinataKeys = require("./PinataKeys").default;
```

In `frontend/src/App.svelte`:
```
-          data.status === 200 &&
+          data.status === true &&
 ```

**Comment by lantonmills** [comment]
Thank you!!

**Comment by BakeTz** [comment]
Hi @claudebarde, @maddybvh I try to originate a contract on https://ide.ligolang.org/ and get several errors like:

Error: File "/tmp/tmp-7zpZOuG20WHf2.ligo", line 283, characters 20-22:
Invalid symbol: "&&".
Hint: Check the LIGO syntax you use.

Error: File "/tmp/tmp-7wr0zkPYxyyZC.ligo", line 68, characters 27-29:
Invalid symbol: "<>".
Hint: Check the LIGO syntax you use.
 
Error: File "/tmp/tmp-7gW0q5sJDNSxg.ligo", line 378, characters 27-29:
Invalid symbol: "<>".
Hint: Check the LIGO syntax you use.
 
Error: File "/tmp/tmp-7EYaT5I9GRcrk.ligo", line 385, characters 17-19:
Invalid symbol: "<>".
Hint: Check the LIGO syntax you use.

Error: File "/tmp/tmp-7cSm5M47cC2Mt.ligo", line 402, characters 42-44:
Invalid symbol: "::".
Hint: Check the LIGO syntax you use.

Error: File "/tmp/tmp-7U5njzOjQuyKj.ligo", line 410, characters 79-81:
Invalid symbol: "::".
Hint: Check the LIGO syntax you use.
....

I run under PascaLIGO and Configure "Compile Contract". Also, I don't understand how can I connect my waller/address to the contract in the ide.ligolang.org site.

Please HELP!

**Comment by claudebarde** [comment]
Hey @BakeTz, the contract is written in CameLigo, so you cannot compile it as a PascaLigo contract.

**Comment by claudebarde** [comment]
> Hi @claudebarde , thanks for the great article! I ran into two small issues setting this up locally.
> 
> I'm not able to submit a PR, but in case anyone comes across this, these are the changes I needed to make:
> 
> In `backend/src/index.ts`:
> 
> ```
> -  const PinataKeys = require("./PinataKeys");
> +  const PinataKeys = require("./PinataKeys").default;
> ```
> 
> In `frontend/src/App.svelte`:
> 
> ```
> -          data.status === 200 &&
> +          data.status === true &&
> ```

I will look into that, thank you!

**Comment by DappGuy** [comment]
> Hey @BakeTz, the contract is written in CameLigo, so you cannot compile it as a PascaLigo contract.

i compile in CameLigo but still get the same error

https://ide.ligolang.org/p/hvW3KEZXlTuuaQVFBGPZLQ


https://ide.ligolang.org/p/hvW3KEZXlTuuaQVFBGPZLQ
ID (CameLIGO)
502503504505506507508509510511512513514515516517518519520521522523524525526527528529530531532533534535536
}

{"version":"v1.0.0","name":"TUTs","authors":["@claudebarde"],"interfaces":["TZIP-012","TZIP-016"]}


*)
Error: File "/tmp/tmp-8caDzHy6MQ3qf.ligo", line 283, characters 20-22:
Invalid symbol: "&&".
Hint: Check the LIGO syntax you use.

**Comment by claudebarde** [comment]
The error was due to a bug in the Ligo web IDE. It has been fixed now and you should be able to compile the contract properly.

**Comment by sb-saksham** [comment]
Can I use this contract for a Tezos Hackathon?

**Comment by claudebarde** [comment]
Sure :)

**Comment by paulmreese** [comment]
@maddybvh Thank you so much for the suggestion! I was losing my mind trying to figure this out.
@claudebarde and thank YOU for this repo!

**Comment by reganwillis** [comment]
After clicking the upload button I was getting an app crash and the error: "No pinataApiKey provided! Please provide your pinata api key as an argument when you start this script". @maddybvh 's above suggestions fixed the problem.

Great repo!

**Comment by claudebarde** [comment]
The repo has now been updated, thank you @maddybvh !
