### ISSUE TITLE
Florencenet is deprecated

### ISSUE THREAD

**Issue by vectris-dev** [claudebarde/taquito-pinata-tezos-nft#2]
Hi @claudebarde, thanks for the excellent tutorial. I think I almost have it working however Florencenet is deprecated as of [August 6, 2021](https://tezos.gitlab.io/introduction/test_networks.html#florencenet)

I assume changing the references to Hangzhounet will fix this however I'm unable to submit a PR

Cheers!

**Comment by vectris-dev** [comment]
Actually I get issues CORS issues with Hangzhounet

`localhost/:1 Access to XMLHttpRequest at 'https://api.tez.ie/rpc/hangzhounet/chains/main/blocks/head/context/contracts/KT1VCvTmJJLA7k4UBKFS13FmaBgr32HAKygi/script' from origin 'http://localhost:8082' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by claudebarde** [comment]
Hi @steve-hadley, thank you for your feedback!
I updated the frontend app and upgraded it to Hangzhounet. The CORS issue you mentioned probably came from a deprecated URL to access Taquito's public node, it was fixed too. Let me know if you experience further issues, thanks!
