### ISSUE TITLE
CORS issue with connection to IthacaNet

### ISSUE THREAD

**Issue by a-breezy** [claudebarde/taquito-pinata-tezos-nft#3]
Not certain what the problem is, but it's connected to CORs not allowing Ithacanet to connect.

Probably related to ithacanet returning 404 on request

**Comment by claudebarde** [comment]
Can you copy-paste the exact error message you get? Thanks!

**Comment by a-breezy** [comment]
I'm sorry, I meant to add this issue to my fork of your code!
I think the issue is related to using Ithacanet instead of Hangzhaou, but this is the error message:

```
HttpResponse: Http error response: (404) 
    at XMLHttpRequest.request.onload (http://localhost:8082/build/bundle.js:13285:28)
```
