### ISSUE TITLE
still having issues building

### ISSUE THREAD

**Issue by jimijon** [claudebarde/taquito-pinata-tezos-nft#7]
Frontend built, backend no:

12   pinata = pinataSDK(process.env.PINATA_API_KEY, process.env.PINATA_SECRET_KEY);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:15:12 - error TS2348: Value of type 'typeof PinataClient' is not callable. Did you mean to include 'new'?

15   pinata = pinataSDK(PinataKeys.apiKey, PinataKeys.apiSecret);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/index.ts:12

npm ERR! code 2
npm ERR! path /Users/James/taquito-pinata-tezos-nft/backend
npm ERR! command failed
npm ERR! command sh -c tsc

**Comment by claudebarde** [comment]
It's fixed.
Next time, you can fix it yourself and create a PR, it's an open-source project after all :)

**Comment by jimijon** [comment]
Fair enough. Sent from my iPhoneOn Feb 6, 2023, at 9:33 AM, 'Claude Barde' via github ***@***.***> wrote:﻿
It's fixed.
Next time, you can fix it yourself and create a PR, it's an open-source project after all :)
